services:
  traefik:
    image: traefik:v2.10.7
    ports:
      - "80:80"
      - "443:443"
      # remove port 8080 for production
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml
      - ./traefik/ssl/:/ssl-certs/
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "3"

  optimal-settings-frontend:
    build: optimal-settings-frontend
    ports:
      - 3000:3000
    environment:
      - BACKEND_PROTOCOL=http
      - BACKEND_HOST=optimal-settings-backend
      - BACKEND_PORT=3001
      - PUBLIC_BACKEND_PROTOCOL=https
      - PUBLIC_BACKEND_HOST=api.localhost
      - PUBLIC_BACKEND_PORT=443
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.optimal-settings-frontend.rule=Host(`localhost`)"
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "3"

  optimal-settings-backend:
    build: optimal-settings-backend
    ports:
      - 3001:3001
    environment:
      - DATABASE_URL=sqlite:data/db/optimal-settings.db
      - JWT_SECRET=secret
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=password
    volumes:
      - data:/app/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.optimal-settings-backend.rule=Host(`api.localhost`)"
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "3"

volumes:
  data: {}
