on: [push, pull_request]

name: Frontend Continuous Integration

defaults:
  run:
    shell: bash
    working-directory: ./optimal-settings-frontend

jobs:
  lints:
    name: Lints
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies
        run:  npm ci

      - name: Run lints
        run: npm run lint
        
      - name: Run prettier check
        run: npm run check-format

  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies
        run:  npm ci

      - name: Run build
        run: npm run build

